"""
PS13 Hardware Security — Timing Analyzer (SCA Module)
======================================================
Parses Vivado timing reports and compares timing characteristics
between clean and Trojan-infected designs.

Analyzes:
  - Critical path delays
  - Slack values (setup/hold)
  - Path endpoint analysis
  - Timing differences between reference and suspect designs
  - Statistical comparison of timing distributions

IMPORTANT: This module uses REAL Vivado timing data — not invented numbers.
A timing difference is NOT automatically an "SCA attack" — it requires:
  1. A defined observable
  2. A measurement procedure
  3. A reference condition
  4. A statistical comparison criterion
"""

import os
import re
import json
from typing import Dict, List, Any, Optional, Tuple


class TimingAnalyzer:
    """
    Parse and compare Vivado timing reports for SCA analysis.

    Reads .rpt files generated by Vivado's report_timing command
    and extracts delay, slack, and path information.
    """

    def __init__(self):
        """Initialize timing analyzer."""
        self.reference_data = None  # Clean design timing
        self.suspect_data = None    # Trojan-infected design timing
        self.comparison = None

    def parse_timing_report(self, report_path: str) -> Dict[str, Any]:
        """
        Parse a Vivado timing report file.

        Args:
            report_path: Path to the .rpt file.

        Returns:
            Dictionary of extracted timing data.
        """
        if not os.path.exists(report_path):
            raise FileNotFoundError(f"Timing report not found: {report_path}")

        with open(report_path, 'r') as f:
            content = f.read()

        timing_data = {
            "file": report_path,
            "paths": [],
            "summary": {}
        }

        # Extract WNS (Worst Negative Slack)
        wns_match = re.search(r'WNS\s*\(ns\)\s*:\s*([-\d.]+)', content)
        if wns_match:
            timing_data["summary"]["wns_ns"] = float(wns_match.group(1))

        # Extract TNS (Total Negative Slack)
        tns_match = re.search(r'TNS\s*\(ns\)\s*:\s*([-\d.]+)', content)
        if tns_match:
            timing_data["summary"]["tns_ns"] = float(tns_match.group(1))

        # Extract WHS (Worst Hold Slack)
        whs_match = re.search(r'WHS\s*\(ns\)\s*:\s*([-\d.]+)', content)
        if whs_match:
            timing_data["summary"]["whs_ns"] = float(whs_match.group(1))

        # Extract individual timing paths
        path_pattern = re.compile(
            r'Slack\s*\((\w+)\)\s*:\s*([-\d.]+)ns.*?'
            r'Source:\s*(\S+).*?'
            r'Destination:\s*(\S+).*?'
            r'Data Path Delay:\s*([\d.]+)ns',
            re.DOTALL
        )
        for match in path_pattern.finditer(content):
            slack_type, slack_val, source, dest, delay = match.groups()
            timing_data["paths"].append({
                "slack_type": slack_type,
                "slack_ns": float(slack_val),
                "source": source,
                "destination": dest,
                "data_path_delay_ns": float(delay)
            })

        # Extract timing summary table if present
        timing_data["summary"]["path_count"] = len(timing_data["paths"])
        if timing_data["paths"]:
            delays = [p["data_path_delay_ns"] for p in timing_data["paths"]]
            slacks = [p["slack_ns"] for p in timing_data["paths"]]
            timing_data["summary"]["max_delay_ns"] = max(delays)
            timing_data["summary"]["min_delay_ns"] = min(delays)
            timing_data["summary"]["avg_delay_ns"] = round(sum(delays) / len(delays), 3)
            timing_data["summary"]["min_slack_ns"] = min(slacks)

        return timing_data

    def load_reference(self, report_path: str) -> None:
        """Load clean design timing report as reference."""
        self.reference_data = self.parse_timing_report(report_path)

    def load_suspect(self, report_path: str) -> None:
        """Load suspect (potentially Trojan-infected) design timing report."""
        self.suspect_data = self.parse_timing_report(report_path)

    def compare(self) -> Dict[str, Any]:
        """
        Compare reference and suspect timing data.

        Returns:
            Dictionary with comparison results and anomalies.
        """
        if self.reference_data is None or self.suspect_data is None:
            raise RuntimeError("Both reference and suspect reports must be loaded.")

        ref_summary = self.reference_data["summary"]
        sus_summary = self.suspect_data["summary"]

        self.comparison = {
            "reference_file": self.reference_data["file"],
            "suspect_file": self.suspect_data["file"],
            "delay_comparison": {
                "ref_max_delay_ns": ref_summary.get("max_delay_ns", 0),
                "sus_max_delay_ns": sus_summary.get("max_delay_ns", 0),
                "delta_max_delay_ns": round(
                    sus_summary.get("max_delay_ns", 0) -
                    ref_summary.get("max_delay_ns", 0), 3
                ),
                "ref_avg_delay_ns": ref_summary.get("avg_delay_ns", 0),
                "sus_avg_delay_ns": sus_summary.get("avg_delay_ns", 0),
                "delta_avg_delay_ns": round(
                    sus_summary.get("avg_delay_ns", 0) -
                    ref_summary.get("avg_delay_ns", 0), 3
                ),
            },
            "slack_comparison": {
                "ref_wns_ns": ref_summary.get("wns_ns", 0),
                "sus_wns_ns": sus_summary.get("wns_ns", 0),
                "ref_min_slack_ns": ref_summary.get("min_slack_ns", 0),
                "sus_min_slack_ns": sus_summary.get("min_slack_ns", 0),
            },
            "path_count_comparison": {
                "ref_paths": ref_summary.get("path_count", 0),
                "sus_paths": sus_summary.get("path_count", 0),
                "delta_paths": (sus_summary.get("path_count", 0) -
                                ref_summary.get("path_count", 0)),
            },
            "anomalies": self._find_timing_anomalies()
        }

        return self.comparison

    def _find_timing_anomalies(self) -> List[Dict]:
        """
        Identify timing paths that differ significantly between designs.
        """
        anomalies = []

        # Compare paths by endpoint matching
        ref_endpoints = {}
        for path in self.reference_data.get("paths", []):
            key = (path["source"], path["destination"])
            ref_endpoints[key] = path

        for path in self.suspect_data.get("paths", []):
            key = (path["source"], path["destination"])
            if key in ref_endpoints:
                ref_delay = ref_endpoints[key]["data_path_delay_ns"]
                sus_delay = path["data_path_delay_ns"]
                delta = sus_delay - ref_delay

                # Flag if delay changed by more than 10%
                if ref_delay > 0 and abs(delta) / ref_delay > 0.10:
                    anomalies.append({
                        "source": path["source"],
                        "destination": path["destination"],
                        "ref_delay_ns": ref_delay,
                        "sus_delay_ns": sus_delay,
                        "delta_ns": round(delta, 3),
                        "percent_change": round(delta / ref_delay * 100, 1),
                    })
            else:
                # Path exists in suspect but not reference — new path
                anomalies.append({
                    "source": path["source"],
                    "destination": path["destination"],
                    "ref_delay_ns": None,
                    "sus_delay_ns": path["data_path_delay_ns"],
                    "delta_ns": None,
                    "percent_change": None,
                    "note": "New path not present in reference design"
                })

        return anomalies

    def to_json(self, output_path: str) -> None:
        """Export comparison results to JSON."""
        if self.comparison is None:
            self.compare()
        with open(output_path, 'w') as f:
            json.dump(self.comparison, f, indent=2)
